### PR TITLE
Theme Cleanup and Login UI

### PR DESCRIPTION
**Pull request by abhi40308**
This pr contains:
* Set up base repository
* Theme cleanup
* Login component UI
Screenshot 2020-06-27 at 4 27 30 AM
Screenshot 2020-06-27 at 4 27 36 AM

### CODE REVIEW

**Comment by abhi40308** [comment]
This has only login UI, as I wanted to see how routes etc worked in theme. I will complete the authentication part in another pr.

**Comment by giorgiozoppi** [comment]
Ok, there is too much empty space in the login page. Please consider something like this. The idea is to have initially two columns, one for the login and the other for something to say about the product.
mifos

**Comment by giorgiozoppi** [comment]
Once up please perform Lighhouse testing https://developers.google.com/web/tools/lighthouse

**Comment by abhi40308** [comment]
@giorgiozoppi Sure, I will change the login screen, it was just for testing screen. I am sending a separate pr for login, in which I will update it. I am merging this pr for now to build a base repo.

**Comment by giorgiozoppi** [comment]
From my side after work i will dedicate you time to solve compatibilities issues. We might want the last version of everything.

**Pull request merged**
